services:
  duel6r-windows-dev:
    image: ghcr.io/mkapusnik/duel6r-build-w64:develop
    entrypoint: /bin/bash
    command: -lc "trap 'exit 0' TERM INT; while sleep 3600; do :; done"
    working_dir: /workspace
    init: true
    volumes:
      - ..:/workspace:cached
    environment:
      OUTPUT_DIR: build
      CLEAN_OUTPUT_DIR: "OFF"
      BUILD_TYPE: Release
      D6R_RENDERER: gl4
      D6R_WITH_LUA: "ON"
      BUILD_TESTING: "ON"
      RUN_TESTS: "OFF"
