name: Develop - Nightly Scheduler
on:
  schedule:
    - cron: "0 * * * *"
#    - cron: "0 4,20 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  scheduler:
    name: Scheduler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: gh workflow disable "${{ github.workflow }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: gh workflow run nightly-builds.yml --ref sanity
        env:
          GH_TOKEN: ${{ secrets.PAT }}