name: Develop - Sanity check
on:
  push:
    branches: [ develop ]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sanity:
    name: Sanity Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker release image
        run: docker build .

  tag:
    name: Tag - sanity
    permissions:
      contents: 'write'
    runs-on: ubuntu-latest
    needs: [sanity]
    steps:
      - uses: actions/checkout@v6

      - uses: mkapusnik/commons/.github/actions/tag@master
        with:
          tag: sanity
          token: ${{ secrets.PAT }}

      - run: gh workflow enable develop-nightly-scheduler.yml
        env:
          GH_TOKEN: ${{ secrets.PAT }}
